DROP TABLE IF EXISTS `PRODUCT_CART`;
DROP TABLE IF EXISTS `PRODUCT`;
DROP TABLE IF EXISTS `CART`;

CREATE TABLE `PRODUCT` (
	`PRO_CODE` BIGINT(10) NOT NULL AUTO_INCREMENT,
	`PRO_DESCRIPTION` VARCHAR(255) NOT NULL,
	`PRO_STOCK` INT(10) NOT NULL,
	`PRO_UNIT_PRICE` DECIMAL(9,2) NOT NULL,
	`PRO_CREATED_DATE` DATE DEFAULT TODAY(),
	PRIMARY KEY (`PRO_CODE`));

CREATE TABLE `CART` (
	`CRT_CODE` BIGINT(10) NOT NULL AUTO_INCREMENT,
	`CRT_FULL_NAME` VARCHAR(255) NOT NULL,
	`CRT_EMAIL` VARCHAR(255) NOT NULL,
	`CRT_STATUS` VARCHAR(255) DEFAULT 'NEW',
	`CRT_CREATED_DATE` DATE DEFAULT TODAY(),
	PRIMARY KEY (`CRT_CODE`));

CREATE TABLE `PRODUCT_CART` (
	`PRO_CODE` BIGINT(10)  NOT NULL,
	`CRT_CODE` BIGINT(10)  NOT NULL,
	`PRO_CTR_CREATED_DATE` DATE DEFAULT TODAY(),
	`PRO_CTR_QTY` INT(10) NOT NULL,
	`PRO_CTR_UNIT_PRICE` DECIMAL(9,2) NOT NULL,
	PRIMARY KEY (`PRO_CODE`, `CRT_CODE`),
	CONSTRAINT `FK_PRO_CODE` FOREIGN KEY (`PRO_CODE`) REFERENCES `PRODUCT` (`PRO_CODE`),
	CONSTRAINT `FK_CRT_CODE` FOREIGN KEY (`CRT_CODE`) REFERENCES `CART` (`CRT_CODE`));